CREATE TABLE HYPERLINKS(
                        ID bigint NOT NULL,
                        LINK VARCHAR(100) NOT NULL
);
ALTER TABLE IF EXISTS HYPERLINKS ADD CONSTRAINT pk_link_id  PRIMARY KEY (ID) ;
CREATE SEQUENCE sq_link_id START WITH 1 INCREMENT BY 1;
ALTER TABLE IF EXISTS HYPERLINKS ADD CONSTRAINT unique_hyperlinks_link UNIQUE(LINK);

CREATE TABLE HYPERLINKS_USERAPP(
                           ID_USERAPP bigint NOT NULL,
                           ID_HYPERLINKS bigint NOT NULL,
                           KEY_WORD VARCHAR(25) NOT NULL,
                           start_Monitoring DATE NOT NULL

);
ALTER TABLE IF EXISTS HYPERLINKS_USERAPP ADD CONSTRAINT sq_hyperliks_userapp_id  PRIMARY KEY (ID_USERAPP,ID_HYPERLINKS,KEY_WORD);
ALTER TABLE IF EXISTS HYPERLINKS_USERAPP
    ADD CONSTRAINT fk_hyperlinks_id FOREIGN KEY (ID_HYPERLINKS) REFERENCES HYPERLINKS(ID);
ALTER TABLE IF EXISTS HYPERLINKS_USERAPP
    ADD CONSTRAINT fk_userapp_in_hyperlinks_id FOREIGN KEY (ID_USERAPP) REFERENCES USERAPP(ID);