CREATE TABLE HYPERLINKS(
                        ID bigint NOT NULL,
                        LINK VARCHAR(100) NOT NULL
);
ALTER TABLE IF EXISTS HYPERLINKS ADD CONSTRAINT pk_link_id  PRIMARY KEY (ID) ;
CREATE SEQUENCE sq_link_id START WITH 1 INCREMENT BY 1;
ALTER TABLE IF EXISTS HYPERLINKS ADD CONSTRAINT unique_hyperlinks_link UNIQUE(LINK);

CREATE TABLE HYPERLINKS_USER_APP(
                           ID_USER_APP bigint NOT NULL,
                           ID_HYPERLINKS bigint NOT NULL,
                           KEY_WORD VARCHAR(25) NOT NULL,
                           LINK_ARTICLE VARCHAR(25) NOT NULL
);
ALTER TABLE IF EXISTS HYPERLINKS_USER_APP ADD CONSTRAINT sq_hyperlinks_user_app_id  PRIMARY KEY (ID_USER_APP,ID_HYPERLINKS,KEY_WORD);
ALTER TABLE IF EXISTS HYPERLINKS_USER_APP
    ADD CONSTRAINT fk_hyperlinks_id FOREIGN KEY (ID_HYPERLINKS) REFERENCES HYPERLINKS(ID);
ALTER TABLE IF EXISTS HYPERLINKS_USER_APP
    ADD CONSTRAINT fk_user_app_in_hyperlinks_id FOREIGN KEY (ID_USER_APP) REFERENCES USER_APP(ID);