CREATE TABLE USERAPP(
                        ID bigint NOT NULL,
                        FIRST_NAME VARCHAR(25) NOT NULL,
                        LAST_NAME VARCHAR(25) NOT NULL,
                        PATRONYMIC VARCHAR(25),
                        EMAIL VARCHAR(25) NOT NULL,
                        LOGIN VARCHAR(25) NOT NULL,
                        HASH_PASSWORD VARCHAR(255) NOT NULL
);
ALTER TABLE IF EXISTS USERAPP ADD CONSTRAINT pk_userapp_id  PRIMARY KEY (ID) ;
CREATE SEQUENCE sq_userapp_id START WITH 1 INCREMENT BY 1;
ALTER TABLE IF EXISTS USERAPP ADD CONSTRAINT unique_userapp_login UNIQUE(LOGIN);



CREATE TABLE ROLE(
                     ID BIGINT NOT NULL,
                     NAME VARCHAR(15) NOT NULL
);
ALTER TABLE IF EXISTS ROLE
    ADD CONSTRAINT pk_role_id PRIMARY KEY (ID);
CREATE SEQUENCE sp_role_id START WITH 1 INCREMENT BY 1;
ALTER TABLE IF EXISTS ROLE
    ADD CONSTRAINT unique_role_name UNIQUE(NAME);



CREATE TABLE ROLE_USERAPP(
                          ID_USERAPP BIGINT NOT NULL,
                          ID_ROLE BIGINT NOT NULL
);
ALTER TABLE IF EXISTS ROLE_USERAPP
    ADD CONSTRAINT pk_role_user_id PRIMARY KEY (ID_USERAPP,ID_ROLE);
ALTER TABLE IF EXISTS ROLE_USERAPP
    ADD CONSTRAINT fk_role_id FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID);
ALTER TABLE IF EXISTS ROLE_USERAPP
    ADD CONSTRAINT fk_userapp_id FOREIGN KEY (ID_USERAPP) REFERENCES USERAPP(ID);

